negative_review = """You know that foreign exchange student from high school who used to creep out all the girls with his clumsy leering and broken-English pick-up lines? Well, he's all grown up and somebody gave him money to make a film. Tommy Wiseau, whose accent could best be described as "half-drunk Croatian cyborg", stars as Johnny, the man with the most sculpted ass in all of San Francisco. His girlfriend Lisa, played by oft-topless Juliette Danielle, seduces his best friend, played by department store mannequin Greg Sestero. To go any farther with the plot would be overdignifying this laugh-out-loud crapfest. Imagine a two-hour episode of "Red Shoe Diaries" written and directed by Balki from "Perfect Strangers". Trust me, this is the worst movie you will ever see ever in your entire life. Ever. But is it pathetically awful or sadistically hilarious? What you think will depend on your life experiences and viewpoint. But we can all agree, it's a big, steaming nut-filled turd"""

negative_review2 = """I hate this. I want to tell you guys that this was Shyamalan's comeback and that this film is just as terrifying as you've been promised. But, I cannot.

The film starts off actually quite well. Minus some less than stellar acting (in fact, its horrible) and some just as bad dialogue, I really thought that maybe this film could pull it off. Disturbing death scenes ensue.

Then, bring in Mark Wahlberg. What happened to this guy? Nominated for an Oscar for his turn in The Departed, Wahlberg seems like a safe bet, but in actuality, he's playing a role that just isn't made for him. This role was made for someone nicer. Walhberg has been typecast time and time again as the angry and bad-ass guy, and now I see why. He's good at that and god awful at being nice.

No one else is particularly good either. Zoey Deschanel disappoints, John Leguizamo (Everyone in this movie has a name that's difficult to spell), and all of the extras are just as bad. There is not a single moment of good acting in this movie.

And all of that is because of how rushed this film feels. This is one of those movies that it seriously felt like the director was working on a very limited budget and then took the first take for every actor, none of them had a chance to get into their roles (or so I hope).

It's obvious who will get all of the blame for this (M. Night Shyamalan) and it's really too bad. I can't say that the plot is necessarily bad, it isn't, and with maybe one more draft the script would've been good. The faults of this film all land on Night's shoulders though. I hate to say it because I am very much not a hater of his (I love The Sixth Sense, Unbreakable, and Signs) but I'm forced to say I hate this movie. Not so much for how bad it actually is (it's very bad) but because I really had faith in the director. The trailers almost felt promising and Shyamalan (am I even spelling this right?) promised me that I'd walk out shaking. Instead, I was shaking my head in disappointment.

One thing I'd like to add on though, I can tell that they were going for a Hitchcock vibe and the best way I feel that I can describe this is "a very bad version of The Birds." That is all."""

negative_review3 = """I was honestly surprised by Alone in the Dark. It was so bad, I could hardly believe what I was seeing. There are no characters, just a few stereotypes wandering around and getting killed. The extent of the character development was giving each character a name and an occupation, and that's about it. There was no real plot, and none of the characters seemed to have any motivation. In fact, many action scenes just began on their own, coming from nowhere with a pounding techno track. While I was watching this movie I kept asking "Where is this happening? What's going on?" The acting was high school drama quality, with stiff wooden delivery, as though the actors were reading from cue cards without comprehending their lines. Their trouble delivering lines was made even more obvious by horrible sound design. ADR sounded like it was recorded in an open room. The actors were constantly taking obvious care to hit their marks, looking almost robotic in their movements. So, these listless automatons are whisked through a series of implausible and confusing scenarios, often without even the benefit of transition scenes. They were here, now they're there. This was happening, now that's happening. Random scenes with little rhyme or reason. I had a lot of fun watching it. Definitely not worth nine bucks though."""

positive_review = """I was extremely lucky to get the chance to see this film upon its first day release, before entering the cinema, my expectations were already high, after all, this was a film from the cinematic genius who brought us the likes of 'Inception' and 'The Dark Knight', to summarise the following review in a single sentence: I left the cinema in extreme awe from the visual masterpiece I had just viewed. A film that explores the psychological and emotional state of a man whose life revolves around his family, 'Interstellar' is a thrilling and thought-provoking film that boasts an intellectual story masterfully written by the Nolan brothers. Whilst there seems to have been influence from films like '2001: A Space Odyssey' and 'Apollo 13', 'Interstellar' is unique in its own way. Whilst the subject may be hard to comprehend at times, it can't be denied how visually monumental and thoughtful Christopher Nolan's epic science fiction masterpiece is, and can easily be named the best film of this year and possibly one of the greatest science fiction films to have ever graced the screen. A sheer brilliant feat of cinema."""

positive_review2 = """Logan is easily the best Marvel movie ever and almost as good as the Dark Knight. I had a chance to see the premiere. The movie is just over 2 hours. The first 45 minutes and the last 45 minutes are the best part of this film. I have never seen a superhero movie like this. It's brutal to its core. I have a request to Marvel & Fox. Please retire Wolverine character because no one could portray it with this much perfection as Hugh Jackman. This is easily my second favorite movie of this genre. Congrats for Fox to reviving their X-men universe after the Apocalypse mess. X-23 actress is gonna be a big star in the future. Oh man, she's awesome. And this is Patrick Stewart's best performance till date. The villain character was also good, unlike other Marvel movies. Hope MCU will learn from this movie. DCEU also have a lesson or two to learn from Logan about making a dark and gritty film. Overall, I would rate this movie as the second best movie ever in its genre with almost no negatives."""

positive_review3 = """I have just come out of the "Dark Curtain" Screening for The Dark Knight in Adelaide, and I'm blown away.

Nolan's directing is sublime, the pacing of the movie was so well kept, managing to keep the audience enthralled in an almost 3 hour movie. There were several shots in the film that had me saying "Now how in the hell did they do that?!", Brilliant scores by James Newton Howard and Hans Zimmer. Every actor shines, no one person steals the film. I don't want to say much about it, because whatever is said cannot do it justice, there is enough hype surrounding it's release, but it's there for a reason. Top Notch film. Bravo to Nolan and his crew for giving a movie that Batman truly deserves."""